### ISSUE TITLE
Desktop VS Desktop VR

### ISSUE THREAD

**Issue by VunemOmnia** [1F1ERCE1/Aleph#4]
**Our team currently lacks experience, and what we are attempting to make is on the level of a AAA game.**
I Don't think our expectations are going to be met by trying to make something like this as our teams first project.  Something that supports my claim is that we have already missed one deadline, and that was a few months ago.

**I believe we should work on a few smaller projects first, that don't involve VR at first, so that our skills as both a team and individuals can be improved. Currently, there isnt much that a lot of the root team is doing, and communication issues have occurred. **

**Create smaller desktop/mobile/VR games in order to gain some more experience with the planned programs.**

**I am not attempting to be a negative Nancy, nor am I trying to offend anyone. I just think team cohesion and communication isn't that great at the moment, and that our skills both as a team and individuals are lacking.(especially for myself) I feel as if people let their personal opinions and feelings get in the way of thinking critically, and/or logically.
It is not logical to start with a giant project right off the bat as a newly created team, unless said teams members have prior experience regarding the type of project.**
Again, I am Not trying to offend anyone, nor am I being an ass for the sake of being an ass. I am stating a few facts, whether you accept them or not. 
Goodbye, ~Ares.

**Comment by VunemOmnia** [comment]
This is Ares speaking^^^

**Comment by VunemOmnia** [comment]
If anyone wants to talk to me about this, PM me or Ping me on discord. Or, alternatively, leave a comment.

**Comment by VunemOmnia** [comment]
nice. we have yet to reach a single milestone...they are being worked on, but they have not been reached.

**Comment by 1F1ERCE1** [comment]
The one missed deadline was a misfortunate loss of time during which nobody could afford to work on this project, and it was placed on hold entirely.  We're past that now, and getting back on track, rushing to come to an earlier release.  Yes, we do lack AAA experience and skill -- However, I disagree about this game being AAA quality.  We have the map, and the ability to build the systems we need.  What you're seeing is the daunting amount of time it takes to make a game, but at the end of the day, that's the business.  We can't ask people to work on smaller projects first, because the division of resources would be too great.  Yes, we may get some of them done if we're lucky, but people will come and go as we work on this project.  We could go for years, and only get people of the same experience level constantly shifting through the studio, and nothing on the game would EVER get done.  Not to mention, when they joined this studio, they expected to work on THIS game.  We can't rightfully tell them to turn around and work on another.  Also, the root team is being incredibly productive, contrary to your observations, and is well above the average of what you'd expect from a part-time student game studio.  I would say you lacked the proper perspective and mistakenly made an improper assertion. Team communication is already good, seeing as to how we can ask people to do work, and they can give us back a product we can put towards the game.  

> It is not logical to start with a giant project right off the bat as a newly created team, unless said teams members have prior experience regarding the type of project.

This would normally be true, but we are either the brave or foolish ones who chose to do so, depending on who you ask... Especially because are anticipating the long-term product be locked together by an equally giant team of volunteer workers.
